version: "3.8"

services:
  isobar-prod:
    image: isobar-prod
    container_name: isobar-prod
    build:
      dockerfile: docker/prod/Dockerfile
      context: .
    expose:
      - 80
    volumes:
      - "${PWD}:/app"
      - "/app/node_modules"
    networks:
      - isobar

networks:
  isobar:
    external: true
