version: "3.8"

services:
  isobar:
    image: isobar
    container_name: isobar
    build:
      dockerfile: docker/dev/Dockerfile
      context: .
    stdin_open: true
    ports:
      - "4000:4000"
    volumes:
      - "${PWD}:/app"
      - "/app/node_modules"
    networks:
      - isobar

networks:
  isobar:
    external: true
